name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  

jobs:      
  CD: 
    name: Continuous Delivery
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Install Dependencies
        uses: npm install

      - name: Get config file
        env: 
          GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run: |
          echo $GOOGLE_SERVICES_64 > google-services.json.b64
          base64 -d -i google-services.json.b64 > google-services.json

      - name: Build and Submit
        run: EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.EAS_APPLE_APP_SPECIFIC_PASSWORD }} eas build --platform all --profile preview --non-interactive --auto-submit-with-profile=preview --no-wait
  